#EXTRA_CFLAGS := -DIPv4 -fpack-struct -I../lwip/lwip/src/include -I../lwip/lwip/src/include/ipv4 -Ixbox/include -O2 -mcpu=pentium -Werror -Wstrict-prototypes -fomit-frame-pointer -pipe -Ui386

O_TARGET := tcpListener.o

include $(TOPDIR)/Rules.make

