EXTRA_CFLAGS := -fomit-frame-pointer -mpreferred-stack-boundary=2#-funroll-loops -I$(TOPDIR)/lib/crypt

O_TARGET :=  2bBootStartup.o 2bBootStartBios.o 2bPicResponseAction.o \
    2bBootLibrary.o

include $(TOPDIR)/Rules.make
