O_TARGET := MenuActions.o VideoMenuActions.o ResetMenuActions.o FlashMenuActions.o IPMenuActions.o HDDMenuActions.o LEDMenuActions.o CDMenuActions.o InfoMenuActions.o URLMenuActions.o KernelPathMenuActions.o InitrdPathMenuActions.o AppendPathMenuActions.o ModchipMenuActions.o ToolsMenuActions.o LCDMenuActions.o SystemMenuActions.o
include $(TOPDIR)/Rules.make
