O_TARGET := MenuActions.o VideoMenuActions.o ResetMenuActions.o FlashMenuActions.o HDDMenuActions.o LEDMenuActions.o CDMenuActions.o InfoMenuActions.o ModchipMenuActions.o ToolsMenuActions.o LCDMenuActions.o SystemMenuActions.o DeveloperMenuActions.o NetworkMenuActions.o EepromEditMenuActions.o XBlastScriptMenuActions.o #BFMBootMenuActions.o
include $(TOPDIR)/Rules.make
