#O_TARGET := TextMenu.o TextMenuInit.o IPMenuInit.o VideoMenuInit.o ResetMenuInit.o FlashMenuInit.o HDDMenuInit.o HDDFlashMenuInit.o LEDMenuInit.o CDMenuInit.o InfoMenuInit.o URLMenuInit.o KernelPathMenuInit.o InitrdPathMenuInit.o AppendPathMenuInit.o BankSelectMenuInit.o
O_TARGET := TextMenu.o TextMenuInit.o IPMenuInit.o VideoMenuInit.o ResetMenuInit.o HDDMenuInit.o HDDFlashMenuInit.o LEDMenuInit.o CDMenuInit.o InfoMenuInit.o URLMenuInit.o BankSelectMenuInit.o ModchipMenuInit.o LCDMenuInit.o SystemMenuInit.o ToolsMenuInit.o DeveloperMenuInit.o NetworkMenuInit.o
include $(TOPDIR)/Rules.make
